[package]
name = "crabbot-plugin-gemini"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
crabbot-core = { path = "../../../crabbot-core" }
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
