[package]
name = "crabbot-daemon"
description = "The Crabbot background daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "crabbot-daemon"
path = "src/main.rs"

[dependencies]
crabbot-runtime = { path = "../crabbot-runtime" }
tokio.workspace = true
