name: Publish

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

      version:
        required: true
        type: string

      prerelease:
        required: true
        type: string

permissions:
  contents: write

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Notes
        uses: actions/download-artifact@v4

        with:
          name: crabbot-release-notes-${{ inputs.version }}
          path: notes

      - name: Download Archives
        uses: actions/download-artifact@v4

        with:
          pattern: crabbot-v${{ inputs.version }}-*
          path: dist
          merge-multiple: true

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2

        with:
          tag_name: ${{ inputs.tag }}
          name: Crabbot ${{ inputs.tag }}
          body_path: notes/release-notes.md
          prerelease: ${{ inputs.prerelease }}
          files: |
            dist/*
