name: Security

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: read

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Audit Rust Dependencies
        uses: rustsec/audit-check@v2

        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Dependency Policy
        uses: EmbarkStudios/cargo-deny-action@v2
