name: Security

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "23 4 * * 1"

permissions:
  contents: read

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: EmbarkStudios/cargo-deny-action@v2
